services:
- type: web
  name: ai_assistant_zendesk
  runtime: python
  repo: https://github.com/GabiCarrionRM/ai_assistant_zendesk
  plan: starter
  envVars:
  - key: LANGFLOW_API_KEY
    sync: false
  - key: PYTHONPATH
    value: .
  - key: PYTHONUNBUFFERED
    value: "1"
  region: oregon
  buildCommand: pip install -r requirements.txt && chmod +x startup_wrapper.py
  startCommand: python startup_wrapper.py
version: "1"