services:
- type: web
  name: ai_assistant_zendesk
  runtime: python
  repo: https://github.com/GabiCarrionRM/ai_assistant_zendesk
  plan: starter
  envVars:
  - key: LANGFLOW_API_KEY
    sync: false
  - key: LANGCHAIN_TRACING
    value: "false"
  - key: LANGFLOW_BACKEND_DEBUG
    value: "true"
  region: oregon
  buildCommand: pip install -r requirements.txt && chmod +x start.sh && chmod +x patch_chroma.py
  startCommand: bash start.sh
version: "1"