services:
  - type: web
    name: langflow-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLOW_PATH
        value: flow.json
